#!/bin/sh

set -e

. ./terraform.conf

if [ "$HWE_KERNEL" = "yes" ]; then
    KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
else
    KERNEL_FLAVORS="generic"
fi

if [ "$HWE_X11" = "yes" ]; then
    XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
fi

case "$ARCH" in
    amd64)
        BOOT_IMAGE="--binary-images iso-hybrid --uefi-secure-boot enable"
        MIRRORS_URL="mirror://mirrors.ubuntu.com/mirrors.txt"
        ;;
    arm64)
        # live-build takes too long to find mirrors for ubuntu-ports
        BOOT_IMAGE="--bootloaders grub-efi --uefi-secure-boot disable"
        MIRRORS_URL="http://mirrors.mit.edu/ubuntu-ports/"
        ;;
esac

lb config noauto \
    --architectures "$ARCH" \
    --mode ubuntu \
    --initramfs none \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages linux-image \
    --linux-flavours "$KERNEL_FLAVORS" \
    --bootappend-live "boot=casper maybe-ubiquity quiet splash" \
    --debootstrap-options="--extractor=ar --keyring=/etc/apt/trusted.gpg" \
    --checksums md5 \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
    --mirror-binary "$MIRRORS_URL" \
    --parent-mirror-binary "$MIRRORS_URL" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--yes --option Acquire::Retries=2 --option Acquire::http::Timeout=45" \
    --cache-packages false \
    --cache-stages false \
    $BOOT_IMAGE \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --zsync false \
    "${@}"

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
